import json
import re

c2010 = [
    "2A0125 - LÓGICA Y ALGORITMOS",
    "2C0187 - LENGUAJE Y REDACCIÓN",
    "380058 - ALGEBRA LINEAL",
    "380103 - MATEMÁTICA BÁSICA",
    "5A0060 - COMPUTACIÓN E INFORMÁTICA BÁSICA",
    "600037 - METODOLOGÍA DE LA INVESTIGACIÓN",
    "880116 - INTRODUCCIÓN A LA INGENIERÍA DE SISTEMAS",
    "380165 - CÁLCULO DIFERENCIAL E INTEGRAL",
    "3A0014 - FÍSICA",
    "700080 - ECONOMÍA",
    "780192 - CONTABILIDAD GENERAL",
    "7A0472 - ADMINISTRACIÓN DE NEGOCIOS",
    "880109 - ALGORITMOS Y ESTRUCTURA DE DATOS",
    "3B0166 - ECUACIONES DIFERENCIALES",
    "5B0110 - ESTADÍSTICA Y PROBABILIDADES",
    "880073 - TEORÍA DE SISTEMAS",
    "8E0035 - LENGUAJE DE PROGRAMACIÓN ESTRUCTURADO",
    "8E0039 - PROGRAMACIÓN LINEAL",
    "8F0123 - ELECTROMAGNETISMO Y ONDAS",
    "380170 - MATEMÁTICAS DISCRETAS",
    "580021 - ESTADÍSTICA INFERENCIAL",
    "600006 - INVESTIGACIÓN OPERATIVA",
    "780184 - COSTOS Y PRESUPUESTOS",
    "8E0036 - LENGUAJE DE PROGRAMACIÓN ORIENTADO A OBJETOS",
    "8F0127 - SISTEMAS DIGITALES",
    "5A0015 - ARQUITECTURA DEL COMPUTADOR",
    "780197 - INGENIERÍA DE PROCESOS DE NEGOCIOS",
    "880110 - ANÁLISIS Y DISEÑO DE SISTEMAS DE INFORMACIÓN",
    "8E0003 - SISTEMAS OPERATIVOS",
    "8E0037 - LENGUAJE DE PROGRAMACIÓN ORIENTADO A WEB",
    "SA0063 - FUNDAMENTOS DE BASE DE DATOS",
    "200109 - SISTEMAS DE GESTIÓN DEL POTENCIAL HUMANO",
    "2A0124 - FILOSOFÍA Y ÉTICA",
    "2H0033 - FUNDAMENTOS DE COMUNICACIONES",
    "7C0081 - INGENIERÍA ECONÓMICA",
    "880059 - INGENIERÍA DE SOFTWARE I",
    "880068 - SISTEMAS DE BASE DE DATOS"
]

c2019 = [
    "01 - INGLÉS I",
    "02 - LENGUAJE Y COMUNICACIÓN",
    "03 - FILOSOFÍA Y ÉTICA",
    "04 - FUNDAMENTOS DE CÁLCULO",
    "05 - METODOLOGÍA DEL TRABAJO UNIVERSITARIO",
    "06 - ACTIVIDADES CULTURALES Y DEPORTIVAS",
    "07 - MATEMÁTICA",
    "08 - INTRODUCCIÓN A LA INGENIERÍA DE SISTEMAS",
    "09 - INGLÉS II",
    "10 - LIDERAZGO Y DESARROLLO PERSONAL",
    "11 - MEDIO AMBIENTE Y DESARROLLO SOSTENIBLE",
    "12 - TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN",
    "13 - SOCIOLOGÍA",
    "14 - TEORÍA DE SISTEMAS",
    "15 - CÁLCULO DIFERENCIAL E INTEGRAL",
    "16 - FUNDAMENTOS DE PROGRAMACIÓN I",
    "17 - INGLÉS III",
    "18 - PSICOLOGÍA ORGANIZACIONAL",
    "19 - ESTADÍSTICA",
    "20 - GEOPOLÍTICA Y REALIDAD NACIONAL",
    "21 - METODOLOGÍA DE LA INVESTIGACIÓN CIENTÍFICA",
    "22 - FÍSICA",
    "23 - ECUACIONES DIFERENCIALES",
    "24 - FUNDAMENTOS DE PROGRAMACIÓN II",
    "25 - PROGRAMACIÓN APLICADA I",
    "26 - GESTIÓN CONTABLE",
    "27 - ESTADÍSTICA II",
    "28 - INVESTIGACIÓN OPERATIVA I",
    "29 - ELECTROMAGNETISMO Y ELECTRÓNICA BÁSICA",
    "30 - MATEMÁTICAS DISCRETAS",
    "32 - INGENIERÍA DE COSTOS Y PRESUPUESTOS",
    "33 - FUNDAMENTOS DE BASES DE DATOS",
    "34 - INGENIERÍA DE PROCESOS DE NEGOCIOS",
    "35 - SISTEMAS DIGITALES Y ARQUITECTURA DE COMPUTADORAS",
    "36 - SISTEMAS OPERATIVOS",
    "37 - DINÁMICA DE SISTEMAS",
    "38 - PROGRAMACIÓN APLICADA II",
    "39 - ADMINISTRACIÓN FINANCIERA",
    "40 - DISEÑO DE BASES DE DATOS",
    "41 - INGENIERÍA DE REQUERIMIENTOS",
    "42 - FUNDAMENTOS DE REDES Y CONECTIVIDAD",
    "43 - ARQUITECTURA DE SOFTWARE"
]

mapping = {
    "2C0187 - LENGUAJE Y REDACCIÓN": "02 - LENGUAJE Y COMUNICACIÓN",
    "2A0124 - FILOSOFÍA Y ÉTICA": "03 - FILOSOFÍA Y ÉTICA",
    "380103 - MATEMÁTICA BÁSICA": "07 - MATEMÁTICA",
    "880116 - INTRODUCCIÓN A LA INGENIERÍA DE SISTEMAS": "08 - INTRODUCCIÓN A LA INGENIERÍA DE SISTEMAS",
    "880073 - TEORÍA DE SISTEMAS": "14 - TEORÍA DE SISTEMAS",
    "380165 - CÁLCULO DIFERENCIAL E INTEGRAL": "15 - CÁLCULO DIFERENCIAL E INTEGRAL",
    "5B0110 - ESTADÍSTICA Y PROBABILIDADES": "19 - ESTADÍSTICA",
    "600037 - METODOLOGÍA DE LA INVESTIGACIÓN": "21 - METODOLOGÍA DE LA INVESTIGACIÓN CIENTÍFICA",
    "3A0014 - FÍSICA": "22 - FÍSICA",
    "3B0166 - ECUACIONES DIFERENCIALES": "23 - ECUACIONES DIFERENCIALES",
    "780192 - CONTABILIDAD GENERAL": "26 - GESTIÓN CONTABLE",
    "600006 - INVESTIGACIÓN OPERATIVA": "28 - INVESTIGACIÓN OPERATIVA I",
    "8F0123 - ELECTROMAGNETISMO Y ONDAS": "29 - ELECTROMAGNETISMO Y ELECTRÓNICA BÁSICA",
    "380170 - MATEMÁTICAS DISCRETAS": "30 - MATEMÁTICAS DISCRETAS",
    "780184 - COSTOS Y PRESUPUESTOS": "32 - INGENIERÍA DE COSTOS Y PRESUPUESTOS",
    "SA0063 - FUNDAMENTOS DE BASE DE DATOS": "33 - FUNDAMENTOS DE BASES DE DATOS",
    "780197 - INGENIERÍA DE PROCESOS DE NEGOCIOS": "34 - INGENIERÍA DE PROCESOS DE NEGOCIOS",
    "8F0127 - SISTEMAS DIGITALES": "35 - SISTEMAS DIGITALES Y ARQUITECTURA DE COMPUTADORAS",
    "8E0003 - SISTEMAS OPERATIVOS": "36 - SISTEMAS OPERATIVOS",
    "7A0472 - ADMINISTRACIÓN DE NEGOCIOS": "39 - ADMINISTRACIÓN FINANCIERA",
    "880068 - SISTEMAS DE BASE DE DATOS": "40 - DISEÑO DE BASES DE DATOS",
    
    # Prudent Programming Match: 
    # Logic & Algorithms -> Fundamentals I
    # Algoritmos y Estructura -> Fundamentals II
    # LPOO -> Prog Aplicada I
    "8E0035 - LENGUAJE DE PROGRAMACIÓN ESTRUCTURADO": "16 - FUNDAMENTOS DE PROGRAMACIÓN I",
    "880109 - ALGORITMOS Y ESTRUCTURA DE DATOS": "24 - FUNDAMENTOS DE PROGRAMACIÓN II",
    "8E0036 - LENGUAJE DE PROGRAMACIÓN ORIENTADO A OBJETOS": "25 - PROGRAMACIÓN APLICADA I",
}

print("### Equivalencias 1 a 1 Seguras ###")
for k, v in mapping.items():
    print(f"- {k[:6]} {k[9:]} ➔ {v[:2]} {v[5:]}")

print("\n### No Convalidables (No tienen equivalente directo o exacto) ###")
for c in c2010:
    if c not in mapping:
        print(f"- {c}")

