# Generated by Django 5.2.17 on 2026-09-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target', models.CharField(max_length=160)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curricular_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=220)),
                ('semester', models.PositiveSmallIntegerField()),
                ('credits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('theory_hours', models.PositiveSmallIntegerField(blank=True, help_text='Horas académicas semanales', null=True)),
                ('practice_hours', models.PositiveSmallIntegerField(blank=True, help_text='Horas académicas semanales', null=True)),
                ('elective_track', models.CharField(blank=True, max_length=120)),
                ('prerequisites', models.ManyToManyField(blank=True, to='core.course')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pre', 'Prematrícula'), ('enroll', 'Matrícula'), ('closed', 'Cerrado')], default='draft', max_length=20)),
                ('max_credits', models.PositiveSmallIntegerField(default=24)),
                ('pre_start', models.DateTimeField(blank=True, null=True)),
                ('pre_end', models.DateTimeField(blank=True, null=True)),
                ('enroll_start', models.DateTimeField(blank=True, null=True)),
                ('enroll_end', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='single_current_period')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.period')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=15)),
                ('official_code', models.CharField(blank=True, max_length=30)),
                ('raw_name', models.CharField(max_length=220)),
                ('cycle', models.CharField(blank=True, max_length=10)),
                ('classroom', models.CharField(blank=True, max_length=60)),
                ('capacity', models.PositiveSmallIntegerField(default=35)),
                ('published', models.BooleanField(default=False)),
                ('source_row', models.CharField(blank=True, max_length=30)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='core.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='core.period')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.enrollment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_lines', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preselection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.period')),
                ('preferred_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preselections', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('passed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.student')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.student'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('plan', 'curricular_code'), name='unique_course_in_plan'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='meeting_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentline',
            constraint=models.UniqueConstraint(fields=('enrollment', 'course'), name='one_section_per_course'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentline',
            constraint=models.UniqueConstraint(fields=('enrollment', 'section'), name='no_duplicate_enrollment_line'),
        ),
        migrations.AddConstraint(
            model_name='preselection',
            constraint=models.UniqueConstraint(fields=('student', 'period', 'course'), name='one_preference_per_course'),
        ),
        migrations.AddConstraint(
            model_name='finalgrade',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'period'), name='unique_grade_attempt'),
        ),
        migrations.AddConstraint(
            model_name='finalgrade',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 20)), name='valid_score_range'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='one_enrollment_per_period'),
        ),
    ]
