# Generated by Django 5.2.17 on 2026-09-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentline',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
