# Generated by Django 5.2.17 on 2026-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_academic_data_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='convalidation_active',
            field=models.BooleanField(default=False),
        ),
    ]
